
map_directory = "maps"
function_directory = "functions"
tag_directory = "dot_axbind"
tag_entry_point = "main.toml"

[options.meta]
escape_sequence = '|'
wildcard_char = '^'

[options.group]
axbind_file_format = '^.axbind'

[options.layer]
key_format = '@^@'
escape_sequence = '@DISABLED'
