
#map_directory = "maps"
function_directory = "functions"
tag_directory = "dot_axbind"

[options.meta]
escape_char = '|'
wildcard_char = '^'

[options.group]
axbind_file_format = '^.axbind'

[options.layer]
key_format = '@^@'
escape_char = '\'
