files = [
    'file_one',
    'file_two'
]

[[layers]]
map = 'testmap_one'
options.key_format = '1^1'
[[layers]]
map = 'testmap_two'
options.key_format = '2^2'
remaps = [ 'testmix' ]
[[layers]]
map = 'testmap_three'
functions = [ 'testfunction_one', 'testfunction_two' ]
options.key_format = '3^3'
